exchange:
    name: binance
    base_snapshot_url: https://api.binance.com/api/v3/depth?symbol={symbol}&limit=1000
    base_ws_url: wss://stream.binance.com/stream?streams=
    pairs:
      # Majors (baseline)
    - symbol: BTCUSDT
    - symbol: ETHUSDT
    - symbol: ETHBTC

    # # Large caps
    - symbol: BNBUSDT
    - symbol: BNBBTC

    # Mid caps intéressantes
    - symbol: ADAUSDT
    - symbol: ADABTC
    - symbol: XRPUSDT
    - symbol: XRPBTC
    - symbol: SOLUSDT
    - symbol: SOLBTC
    - symbol: AVAXUSDT
    - symbol: AVAXBTC
    - symbol: MATICUSDT
    - symbol: MATICBTC 
    - symbol: LINKUSDT
    - symbol: LINKBTC
    - symbol: UNIUSDT
    - symbol: UNIBTC

    # Semi-illiquides (plus d’edge, plus de risque)
    - symbol: APEUSDT
    - symbol: APEBTC
    - symbol: SANDUSDT
    - symbol: SANDBTC
    - symbol: GRTUSDT
    - symbol: GRTBTC
    - symbol: CHZUSDT
    - symbol: CHZBTC

    # Stablecoins (triangles spécifiques)
    - symbol: USDCUSDT
    - symbol: FDUSDUSDT